name: format

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contentsL write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.9"

      - run: make format-project

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "format project"
